server:
  port: 8081

spring:
  application:
    name: order-service


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    data-username: root # temp
    data-password: dogood1!
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialet.MySql8Dialect
    show-sql: true