spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          username:
          password:
          clone-on-start: true
          uri: https://github.com/tosintubi/ms-config.git
  profiles:
    active: native

server:
  port: 8888